create table `data` (

id mediumint not null auto_increment PRIMARY KEY,
name_tracker varchar(255),
app_id varchar(255),
platform varchar(255),
dvce_epoch mediumint default 0,
os_timezone varchar(255),
event varchar(255),
txn_id varchar(255),
v_tracker varchar(255),
domain_userid varchar(255),
network_userid varchar(255),
user_id varchar(255),
domain_sessionidx mediumint default 0,
user_ipaddress varchar(255),
res varchar(255),
page_url varchar(255),
useragent varchar(255),
page_title varchar(255),
page_referrer varchar(255),
user_fingerprint varchar(255),
connection_type varchar(255),
br_cookies tinyint(1) default 0,
br_lang varchar(255),
br_features_pdf tinyint(1) default 0,
br_features_quicktime tinyint(1) default 0,
br_features_realplayer tinyint(1) default 0,
br_features_windowsmedia tinyint(1) default 0,
br_features_director tinyint(1) default 0,
br_features_flash tinyint(1) default 0,
br_features_java tinyint(1) default 0,
br_features_gears tinyint(1) default 0,
br_features_silverlight tinyint(1) default 0,
br_colordepth int default 0,
ds varchar(255),
doc_charset varchar(255),
vp varchar(255),
mac_address varchar(255),
pp_xoffset_min int default 0,
pp_xoffset_max int default 0,
pp_yoffset_min int default 0,
pp_yoffset_max int default 0,
se_category varchar(255),
se_action varchar(255),
se_label varchar(255),
se_property varchar(255),
se_value varchar(255),
unstruct_event text default null,
context text default null

)
engine MyISAM DEFAULT CHARACTER SET = utf8;

CREATE TABLE `raw` ( `id` mediumint(9) NOT NULL AUTO_INCREMENT PRIMARY KEY, `request` text, `created_at` mediumint default 0 ) ENGINE=MyISAM DEFAULT CHARACTER SET = utf8;
