<?php

$map = array(

'tna'    => 'name_tracker',
'aid'    => 'app_id',
'p'      => 'platform',
'dtm'    => 'dvce_epoch',
'tz'     => 'os_timezone',
'e'      => 'event',
'tid'    => 'txn_id',
'eid'    => 'event',
'tv'     => 'v_tracker',
'duid'   => 'domain_userid',
'nuid'   => 'network_userid',
'tnuid'  => 'network_userid',
'uid'    => 'user_id',
'vid'    => 'domain_sessionidx',
'ip'     => 'user_ipaddress',
'res'    => 'res',
'url'    => 'page_url',
'ua'     => 'useragent',
'page'   => 'page_title',
'refr'   => 'page_referrer',
'fp'     => 'user_fingerprint',
'ctype'  => 'connection_type',
'cookie' => 'br_cookies',
'lang'   => 'br_lang',
'f_pdf'  => 'br_features_pdf',
'f_qt'   => 'br_features_quicktime',
'f_realp'=> 'br_features_realplayer',
'f_wma'  => 'br_features_windowsmedia',
'f_dir'  => 'br_features_director',
'f_fla'  => 'br_features_flash',
'f_java' => 'br_features_java',
'f_gears'=> 'br_features_gears',
'f_ag'   => 'br_features_silverlight',
'cd'     => 'br_colordepth',
'ds'     => 'ds',
'cs'     => 'doc_charset',
'vp'     => 'vp',
'mac'    => 'mac_address',
'pp_mix' => 'pp_xoffset_min',
'pp_max' => 'pp_xoffset_max',
'pp_miy' => 'pp_yoffset_min',
'pp_may' => 'pp_yoffset_max',

'se_ca'  => 'se_category',
'se_ac'  => 'se_action',
'se_la'  => 'se_label',
'se_pr'  => 'se_property',
'se_va'  => 'se_value',

'ue_pr'  => 'unstruct_event',
'ue_px'  => 'unstruct_event',

'co'     => 'context',
'cx'     => 'context'

);
